// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";
import { SuspenseWrapper } from "./components/SuspenseWrapper";
import { AuthGuard } from "./components/AuthGuard";

const App = lazy(() => import("./pages/App.tsx"));
const Analytics = lazy(() => import("./pages/AnalyticsPage.tsx"));
const BlogPage = lazy(() => import("./pages/BlogPage.tsx"));
const Chat = lazy(() => import("./pages/Chat.tsx"));
const ChatHistoryPage = lazy(() => import("./pages/ChatHistoryPage.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const DocumentsPage = lazy(() => import("./pages/DocumentsPage.tsx"));
const DocumentCreatePage = lazy(() => import("./pages/create/DocumentCreatePage.tsx"));
const DocumentViewPage = lazy(() => import("./pages/DocumentViewPage.tsx"));
const JobsPage = lazy(() => import("./pages/JobsPage.tsx"));
const LeadsPage = lazy(() => import("./pages/LeadsPage.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Profile = lazy(() => import("./pages/Profile.tsx"));
const Register = lazy(() => import("./pages/Register.tsx"));
const SettingsPage = lazy(() => import("./pages/SettingsPage.tsx"));
const AdminLogin = lazy(() => import("./pages/AdminLogin.tsx"));
const AdminDashboard = lazy(() => import("./components/AdminDashboard.tsx"));

export const userRoutes: RouteObject[] = [
  { path: "/", element: <SuspenseWrapper><App /></SuspenseWrapper>},
  { path: "/login", element: <SuspenseWrapper><Login /></SuspenseWrapper>},
  { path: "/register", element: <SuspenseWrapper><Register /></SuspenseWrapper>},
  { 
    path: "/dashboard", 
    element: <SuspenseWrapper><Dashboard /></SuspenseWrapper>,
    children: [
      { path: "analytics", element: <SuspenseWrapper><Analytics /></SuspenseWrapper>},
      { path: "blog", element: <SuspenseWrapper><BlogPage /></SuspenseWrapper>},
      { path: "chat", element: <SuspenseWrapper><Chat /></SuspenseWrapper>},
      { path: "chat-history", element: <SuspenseWrapper><ChatHistoryPage /></SuspenseWrapper>},
      { path: "documents", element: <SuspenseWrapper><DocumentsPage /></SuspenseWrapper>},
      { path: "documents/create", element: <SuspenseWrapper><DocumentCreatePage /></SuspenseWrapper>},
      { path: "documents/:id", element: <SuspenseWrapper><DocumentViewPage /></SuspenseWrapper>},
      { path: "jobs", element: <SuspenseWrapper><JobsPage /></SuspenseWrapper>},
      { path: "leads", element: <SuspenseWrapper><LeadsPage /></SuspenseWrapper>},
      { path: "profile", element: <SuspenseWrapper><Profile /></SuspenseWrapper>},
      { path: "settings", element: <SuspenseWrapper><SettingsPage /></SuspenseWrapper>},
    ],
  },
  { path: "/admin/login", element: <SuspenseWrapper><AdminLogin /></SuspenseWrapper>},
  { 
    path: "/admin", 
    element: (
      <AuthGuard requireAdmin={true}>
        <SuspenseWrapper>
          <AdminDashboard />
        </SuspenseWrapper>
      </AuthGuard>
    ),
  }
];
