// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject, Outlet } from "react-router-dom";
import { SuspenseWrapper } from "./components/SuspenseWrapper";
import { DashboardMainLayout } from "./components/DashboardMainLayout";
import AuthGuard from "./components/AuthGuard";
import { AdminJobApplications } from './components/AdminJobApplications';
import { ErrorBoundary } from './components/ErrorBoundary';

const App = lazy(() => import("./pages/App.tsx"));
const BlogPage = lazy(() => import("./pages/BlogPage.tsx"));
const BlogPostsPage = lazy(() => import("./pages/BlogPostsPage.tsx"));
const BlogPostEditorPage = lazy(() => import("./pages/blog/BlogPostEditorPage.tsx"));
const BlogPostDetailPage = lazy(() => import("./pages/blog/BlogPostDetailPage.tsx"));
const Chat = lazy(() => import("./pages/Chat.tsx"));
const ChatHistoryPage = lazy(() => import("./pages/ChatHistoryPage.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const DocumentsPage = lazy(() => import("./pages/DocumentsPage.tsx"));
const DocumentCreatePage = lazy(() => import("./pages/create/DocumentCreatePage.tsx"));
const DocumentViewPage = lazy(() => import("./pages/DocumentViewPage.tsx"));
const JobsPage = lazy(() => import("./pages/JobsPage.tsx"));
const LeadsPage = lazy(() => import("./pages/LeadsPage.tsx"));
const Profile = lazy(() => import("./pages/Profile.tsx"));
const SettingsPage = lazy(() => import("./pages/SettingsPage.tsx"));
const AdminLogin = lazy(() => import("./pages/AdminLogin.tsx"));
const AdminDashboard = lazy(() => import("./components/AdminDashboard.tsx"));
const SignIn = lazy(() => import("./pages/SignIn.tsx"));
const SignUp = lazy(() => import("./pages/Register.tsx"));
const CareersPage = lazy(() => import("./pages/company/CareersPage.tsx"));
const ApplicantsPage = lazy(() => import("./pages/ApplicantsPage.tsx"));

export const userRoutes: RouteObject[] = [
  { 
    path: "/", 
    element: <SuspenseWrapper><App /></SuspenseWrapper>
  },
  { 
    path: "/sign-in", 
    element: <SuspenseWrapper><AuthGuard publicOnly><SignIn /></AuthGuard></SuspenseWrapper>
  },
  { 
    path: "/sign-up", 
    element: <SuspenseWrapper><AuthGuard publicOnly><SignUp /></AuthGuard></SuspenseWrapper>
  },
  { 
    path: "/blog", 
    element: <SuspenseWrapper><BlogPage /></SuspenseWrapper>
  },
  { 
    path: "/blog/:id", 
    element: <SuspenseWrapper><BlogPostDetailPage /></SuspenseWrapper>
  },
  { 
    path: "/dashboard",
    element: (
      <AuthGuard>
        <SuspenseWrapper>
          <DashboardMainLayout>
            <Outlet />
          </DashboardMainLayout>
        </SuspenseWrapper>
      </AuthGuard>
    ),
    children: [
      { index: true, element: <SuspenseWrapper><Dashboard /></SuspenseWrapper> },
      { path: "jobs", element: <SuspenseWrapper><JobsPage /></SuspenseWrapper> },
      { path: "applicants", element: <SuspenseWrapper><ApplicantsPage /></SuspenseWrapper> },
      { path: "chat", element: <SuspenseWrapper><Chat /></SuspenseWrapper> },
      { path: "chat-history", element: <SuspenseWrapper><ChatHistoryPage /></SuspenseWrapper> },
      { path: "documents", element: <SuspenseWrapper><DocumentsPage /></SuspenseWrapper> },
      { path: "documents/create", element: <SuspenseWrapper><DocumentCreatePage /></SuspenseWrapper> },
      { path: "documents/:id", element: <SuspenseWrapper><DocumentViewPage /></SuspenseWrapper> },
      { path: "leads", element: <SuspenseWrapper><LeadsPage /></SuspenseWrapper> },
      { path: "blog", element: <SuspenseWrapper><BlogPage /></SuspenseWrapper> },
      { path: "blog-posts", element: <SuspenseWrapper><BlogPostsPage /></SuspenseWrapper> },
      { path: "blog-posts/new", element: <SuspenseWrapper><BlogPostEditorPage /></SuspenseWrapper> },
      { path: "blog-posts/edit/:id", element: <SuspenseWrapper><BlogPostEditorPage /></SuspenseWrapper> },
      { path: "profile", element: <SuspenseWrapper><Profile /></SuspenseWrapper> },
      { path: "settings", element: <SuspenseWrapper><SettingsPage /></SuspenseWrapper> }
    ]
  },
  { 
    path: "/careers", 
    element: (
      <ErrorBoundary>
        <SuspenseWrapper><CareersPage /></SuspenseWrapper>
      </ErrorBoundary>
    )
  },
  { 
    path: "/careers/culture", 
    element: <SuspenseWrapper><CareersPage /></SuspenseWrapper>
  },
  { 
    path: "/careers/benefits", 
    element: <SuspenseWrapper><CareersPage /></SuspenseWrapper>
  },
  { 
    path: "/admin/login", 
    element: <SuspenseWrapper><AuthGuard publicOnly><AdminLogin /></AuthGuard></SuspenseWrapper>
  },
  { 
    path: "/admin", 
    element: <SuspenseWrapper><AuthGuard requireAdmin><AdminDashboard /></AuthGuard></SuspenseWrapper>,
    children: [
      {
        path: "applications",
        element: <SuspenseWrapper><AdminJobApplications /></SuspenseWrapper>
      }
    ]
  }
];
